import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...CORS,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const clean=(v:unknown,max=300)=>typeof v==='string'?v.trim().slice(0,max):'';
const slugify=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)||'exercise';
async function rest(url:string,key:string,path:string,options:RequestInit={}){const r=await fetch(url+path,{...options,headers:{Authorization:`Bearer ${key}`,apikey:key,"Content-Type":"application/json",...(options.headers||{})}});const body=await r.json().catch(()=>null);return {ok:r.ok,status:r.status,body};}

Deno.serve(async(req:Request)=>{
  if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});
  if(req.method!=='POST')return json({error:'method_not_allowed'},405);
  const supabaseUrl=Deno.env.get('SUPABASE_URL')||'',anonKey=Deno.env.get('SUPABASE_ANON_KEY')||'',serviceKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'',openAiKey=Deno.env.get('OPENAI_API_KEY')||'',model=Deno.env.get('OPENAI_IMAGE_MODEL')||'gpt-image-2.5-sunburst',authorization=req.headers.get('Authorization')||'';
  if(!supabaseUrl||!anonKey||!serviceKey||!openAiKey)return json({error:'server_configuration_error'},500);
  if(!authorization.startsWith('Bearer '))return json({error:'unauthorized'},401);
  const userRes=await fetch(`${supabaseUrl}/auth/v1/user`,{headers:{Authorization:authorization,apikey:anonKey}});if(!userRes.ok)return json({error:'unauthorized'},401);
  const user=await userRes.json().catch(()=>null);if(!UUID.test(user?.id||''))return json({error:'unauthorized'},401);
  const actor=await rest(supabaseUrl,serviceKey,`/rest/v1/profiles?id=eq.${encodeURIComponent(user.id)}&select=id,role,status`),profile=Array.isArray(actor.body)?actor.body[0]:null;
  if(!actor.ok||!profile||profile.status!=='active'||!['coach','admin'].includes(profile.role))return json({error:'forbidden'},403);
  const body=await req.json().catch(()=>null),requestId=clean(body?.request_id,60);if(!UUID.test(requestId))return json({error:'valid_request_id_required'},400);
  const loaded=await rest(supabaseUrl,serviceKey,`/rest/v1/exercise_asset_requests_v100?id=eq.${encodeURIComponent(requestId)}&select=*`),job=Array.isArray(loaded.body)?loaded.body[0]:null;if(!loaded.ok||!job)return json({error:'request_not_found'},404);
  if(job.status==='approved'||job.status==='pending_review')return json({request_id:requestId,status:job.status,exercise_id:job.exercise_id,generated_asset_url:job.generated_asset_url,idempotent:true,auto_publish:false});
  if(!['queued','failed'].includes(job.status))return json({error:'request_not_generatable',status:job.status},409);
  await rest(supabaseUrl,serviceKey,`/rest/v1/exercise_asset_requests_v100?id=eq.${requestId}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'generating',error_message:null,updated_at:new Date().toISOString()})});

  let exercise:any=null,isNew=false;
  if(job.exercise_id){const ex=await rest(supabaseUrl,serviceKey,`/rest/v1/exercises?id=eq.${encodeURIComponent(job.exercise_id)}&select=id,name,slug,primary_muscle,equipment,movement_pattern,prescription_unit,instructions,active`);exercise=Array.isArray(ex.body)?ex.body[0]:null;if(!ex.ok||!exercise)return json({error:'exercise_not_found'},404);}else{const spec=job.requested_spec||{},name=clean(spec.name||job.proposed_name,120);if(!name)return json({error:'requested_exercise_name_missing'},422);exercise={name,slug:slugify(name),primary_muscle:clean(spec.primary_muscle,100)||null,equipment:clean(spec.equipment,120)||null,movement_pattern:clean(spec.movement_pattern,120)||null,prescription_unit:['reps','seconds'].includes(spec.prescription_unit)?spec.prescription_unit:'reps',instructions:clean(spec.instructions,1200)||null,active:false};isNew=true;}

  const prompt=`Create ONE premium technical fitness exercise plate for CV Coach. Exercise: ${exercise.name}. Primary muscle: ${exercise.primary_muscle||'not specified'}. Equipment: ${exercise.equipment||'not specified'}. Movement pattern: ${exercise.movement_pattern||'not specified'}.\n\nMANDATORY COMPOSITION: exactly TWO side-by-side panels inside ONE single 3:2 landscape image. Left panel = start position. Right panel = end/contracted position. SAME athlete, SAME clothing, SAME equipment, SAME camera position, SAME camera angle, SAME focal length, SAME gym background and lighting in both panels. The only meaningful difference between panels is the exercise phase. Show the full relevant body and all equipment needed to understand technique. Anatomically correct, realistic biomechanics, safe neutral joint alignment.\n\nVISUAL IDENTITY: premium dark gym, black/charcoal environment, intense controlled red rim lighting/glow, bright white highlights, cinematic depth, high contrast, polished commercial fitness photography, clean framing. Add a subtle metallic silver CV Coach mark with a central red lightning motif and a small clean exercise title '${exercise.name}' without obscuring the athlete. No extra panels, no collage beyond the two phases, no duplicated limbs, no distorted hands, no extra text, no watermark. The two panels MUST be viewed from exactly the same angle.`;
  const started=performance.now();
  const ai=await fetch('https://api.openai.com/v1/images/generations',{method:'POST',headers:{Authorization:`Bearer ${openAiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model,prompt,size:'1536x1024',quality:'medium',n:1})});
  const aiBody=await ai.json().catch(()=>null),latency=Math.round(performance.now()-started),b64=aiBody?.data?.[0]?.b64_json;
  if(!ai.ok||typeof b64!=='string'||!b64){await rest(supabaseUrl,serviceKey,`/rest/v1/exercise_asset_requests_v100?id=eq.${requestId}`,{method:'PATCH',body:JSON.stringify({status:'failed',error_message:`OpenAI image generation failed (${ai.status})`,updated_at:new Date().toISOString()})});return json({error:'image_generation_failed',provider_status:ai.status},502);}
  const raw=Uint8Array.from(atob(b64),(c)=>c.charCodeAt(0)),objectPath=`v100/${exercise.slug}-${requestId.slice(0,8)}.png`;
  const upload=await fetch(`${supabaseUrl}/storage/v1/object/exercise-media/${objectPath}`,{method:'POST',headers:{Authorization:`Bearer ${serviceKey}`,apikey:serviceKey,'Content-Type':'image/png','x-upsert':'true','Cache-Control':'31536000'},body:raw});
  if(!upload.ok)return json({error:'storage_upload_failed'},502);
  const publicUrl=`${supabaseUrl}/storage/v1/object/public/exercise-media/${objectPath}`;
  let exerciseId=job.exercise_id as string|null;
  if(isNew){let slug=exercise.slug;const exists=await rest(supabaseUrl,serviceKey,`/rest/v1/exercises?slug=eq.${encodeURIComponent(slug)}&select=id`);if(Array.isArray(exists.body)&&exists.body.length)slug=`${slug}-${requestId.slice(0,8)}`;const created=await rest(supabaseUrl,serviceKey,'/rest/v1/exercises',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({name:exercise.name,slug,primary_muscle:exercise.primary_muscle,equipment:exercise.equipment,movement_pattern:exercise.movement_pattern,instructions:exercise.instructions,prescription_unit:exercise.prescription_unit,active:false,created_by:user.id})}),row=Array.isArray(created.body)?created.body[0]:null;if(!created.ok||!row?.id)return json({error:'exercise_create_failed'},502);exerciseId=row.id;}
  const registryPayload={exercise_id:exerciseId,source_type:'generated',source_url:null,delivery_url:publicUrl,status:'pending_review',last_checked_at:new Date().toISOString(),approved_at:null,approved_by:null,last_error:null,metadata:{engine_version:'EXERCISE_ASSET_GUARDRAIL_V100',request_id:requestId,model,prompt_version:'CV_EXERCISE_PLATE_V100',generated_new_exercise:isNew,auto_publish:false}};
  const reg=await rest(supabaseUrl,serviceKey,'/rest/v1/exercise_asset_registry_v100?on_conflict=exercise_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(registryPayload)});if(!reg.ok)return json({error:'asset_registry_update_failed'},502);
  await rest(supabaseUrl,serviceKey,`/rest/v1/exercise_asset_requests_v100?id=eq.${requestId}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({exercise_id:exerciseId,status:'pending_review',generated_asset_url:publicUrl,error_message:null,updated_at:new Date().toISOString()})});
  try{const usage=aiBody?.usage||{};await rest(supabaseUrl,serviceKey,'/rest/v1/rpc/record_ai_usage',{method:'POST',body:JSON.stringify({p_response_id:aiBody?.id||null,p_model:model,p_input_tokens:Number(usage.input_tokens||0),p_cached_input_tokens:Number(usage.input_tokens_details?.cached_tokens||0),p_output_tokens:Number(usage.output_tokens||0),p_total_tokens:Number(usage.total_tokens||0),p_latency_ms:latency,p_metadata:{feature:'exercise_asset_generation_v100',request_id:requestId,exercise_id:exerciseId},p_decision_id:null})});}catch(_){/* non-blocking */}
  return json({request_id:requestId,exercise_id:exerciseId,status:'pending_review',generated_asset_url:publicUrl,review_required:true,auto_publish:false,model});
});
