from pathlib import Path

path=Path('client-portal/index.html')
text=path.read_text()

def replace_once(old,new,label):
    global text
    count=text.count(old)
    if count!=1:
        raise SystemExit(f'{label}: expected exactly one anchor, found {count}')
    text=text.replace(old,new,1)

feedback_css=r'''<style id="cv-workout-feedback-v1-css">
.cvFeedbackBackdrop{position:fixed;inset:0;z-index:260;background:rgba(0,0,0,.82);backdrop-filter:blur(8px);display:flex;align-items:flex-end;justify-content:center;padding:14px}
.cvFeedbackCard{width:min(560px,100%);max-height:92dvh;overflow:auto;border:1px solid #303a42;border-radius:20px;background:linear-gradient(155deg,#0d1319,#070b0f);box-shadow:0 28px 90px rgba(0,0,0,.65);padding:18px}
.cvFeedbackCard h2{font-size:30px;margin:4px 0 6px}.cvFeedbackCard .sub{margin-bottom:10px}.cvFeedbackGrid{display:grid;grid-template-columns:1fr;gap:8px}.cvFeedbackGrid label{margin-top:8px}.cvFeedbackCard select,.cvFeedbackCard textarea{width:100%;background:#05090d;border:1px solid #303942;color:#fff;border-radius:12px;min-height:46px;padding:10px 12px;font:inherit;outline:none}.cvFeedbackCard textarea{min-height:88px;resize:vertical}.cvFeedbackCard select:focus,.cvFeedbackCard textarea:focus{border-color:rgba(255,45,63,.86);box-shadow:0 0 0 3px rgba(255,45,63,.09)}.cvFeedbackHint{font-size:10px;line-height:1.45;color:#929da4;margin-top:5px}.cvFeedbackActions{display:grid;grid-template-columns:1fr;gap:8px;margin-top:14px}.cvFeedbackStatus{min-height:20px;margin-top:8px;font-size:11px;color:#aeb8be}.cvFeedbackStatus.error{color:#ff8d99}.cvFeedbackSafety{margin-top:10px;padding:10px 12px;border:1px solid #3a3034;border-radius:12px;background:rgba(225,29,46,.06);font-size:10px;line-height:1.45;color:#c4cdd2}
@media(min-width:700px){.cvFeedbackBackdrop{align-items:center}.cvFeedbackGrid{grid-template-columns:repeat(3,1fr)}.cvFeedbackActions{grid-template-columns:1fr 1.3fr}}
</style>'''
replace_once('</head>',feedback_css+'\n</head>','feedback css')

old="window.finishWorkout=async()=>{if(mode==='demo'){toast('Demo finalizada. No se escribieron datos.');workout=null;view='home';render();return}if(!workout.sessionId)return toast('Primero inicia el entrenamiento.');try{const {data:r,error}=await sb.functions.invoke('complete-workout',{body:{session_id:workout.sessionId}});if(error||r?.error)throw new Error(r?.detail||r?.error||error.message);clearInterval(timerHandle);workout=null;await loadReal();view='home';render();cvShowWorkoutResult(r||{})}catch(e){toast(e.message)}}"

new=r'''function cvFeedbackOptions(min,max,kind){let html='<option value="">Selecciona</option>';for(let i=min;i<=max;i++){let label=String(i);if(kind==='rpe'){if(i<=3)label+=' · Muy suave';else if(i<=5)label+=' · Suave';else if(i<=7)label+=' · Moderado';else if(i===8)label+=' · Duro';else if(i===9)label+=' · Muy duro';else label+=' · Máximo'}else if(kind==='pain'){if(i===0)label+=' · Sin dolor';else if(i<=2)label+=' · Leve';else if(i<=4)label+=' · Moderado';else if(i<=6)label+=' · Alto';else label+=' · Muy alto'}else if(kind==='fatigue'){if(i<=2)label+=' · Muy baja';else if(i<=4)label+=' · Baja';else if(i<=6)label+=' · Moderada';else if(i<=8)label+=' · Alta';else label+=' · Muy alta'}html+='<option value="'+i+'">'+label+'</option>'}return html}
function cvCloseWorkoutFeedback(){document.getElementById('cvWorkoutFeedbackBackdrop')?.remove()}
async function cvCompleteWorkoutAfterFeedback(statusEl,button){try{button.disabled=true;statusEl.classList.remove('error');statusEl.textContent='Guardando feedback y cerrando sesión…';const effort=Number(document.getElementById('cvFeedbackEffort')?.value),fatigue=Number(document.getElementById('cvFeedbackFatigue')?.value),pain=Number(document.getElementById('cvFeedbackPain')?.value),notes=(document.getElementById('cvFeedbackNotes')?.value||'').trim(),painNotes=(document.getElementById('cvFeedbackPainNotes')?.value||'').trim();if(!Number.isInteger(effort)||effort<1||effort>10)throw new Error('Selecciona tu RPE global entre 1 y 10.');if(!Number.isInteger(fatigue)||fatigue<0||fatigue>10)throw new Error('Selecciona tu fatiga entre 0 y 10.');if(!Number.isInteger(pain)||pain<0||pain>10)throw new Error('Selecciona tu nivel de dolor entre 0 y 10.');if(notes.length>1200)throw new Error('El comentario supera el máximo permitido.');if(painNotes.length>500)throw new Error('La descripción de la molestia supera el máximo permitido.');const feedback=await sb.rpc('save_workout_feedback',{p_session_id:workout.sessionId,p_client_effort:effort,p_fatigue_score:fatigue,p_pain_score:pain,p_session_notes:notes||null,p_pain_notes:painNotes||null});if(feedback.error)throw feedback.error;if(!feedback.data?.saved)throw new Error('El backend no confirmó el feedback.');const {data:r,error}=await sb.functions.invoke('complete-workout',{body:{session_id:workout.sessionId}});if(error||r?.error)throw new Error(r?.detail||r?.error||error.message);clearInterval(timerHandle);cvCloseWorkoutFeedback();workout=null;await loadReal();view='home';render();cvShowWorkoutResult(r||{})}catch(e){statusEl.classList.add('error');statusEl.textContent=e?.message||String(e);button.disabled=false}}
function cvOpenWorkoutFeedback(){if(document.getElementById('cvWorkoutFeedbackBackdrop'))return;const modal=document.createElement('div');modal.id='cvWorkoutFeedbackBackdrop';modal.className='cvFeedbackBackdrop';modal.innerHTML='<div class="cvFeedbackCard" role="dialog" aria-modal="true" aria-labelledby="cvFeedbackTitle"><div class="ey">CIERRE DE SESIÓN</div><h2 id="cvFeedbackTitle">¿Cómo se sintió?</h2><div class="sub">Tres datos rápidos ayudan a ajustar tu próxima sesión con más seguridad.</div><div class="cvFeedbackGrid"><div><label for="cvFeedbackEffort">RPE GLOBAL</label><select id="cvFeedbackEffort">'+cvFeedbackOptions(1,10,'rpe')+'</select><div class="cvFeedbackHint">Esfuerzo total de la sesión.</div></div><div><label for="cvFeedbackFatigue">FATIGA</label><select id="cvFeedbackFatigue">'+cvFeedbackOptions(0,10,'fatigue')+'</select><div class="cvFeedbackHint">Cómo quedó tu nivel de fatiga.</div></div><div><label for="cvFeedbackPain">DOLOR / MOLESTIA</label><select id="cvFeedbackPain">'+cvFeedbackOptions(0,10,'pain')+'</select><div class="cvFeedbackHint">0 significa sin dolor.</div></div></div><label for="cvFeedbackPainNotes">¿Dónde sentiste molestia? · opcional</label><textarea id="cvFeedbackPainNotes" maxlength="500" placeholder="Ej.: rodilla derecha, hombro izquierdo…"></textarea><label for="cvFeedbackNotes">Comentario de la sesión · opcional</label><textarea id="cvFeedbackNotes" maxlength="1200" placeholder="Ej.: dormí poco, me sentí fuerte, técnica difícil…"></textarea><div class="cvFeedbackSafety">Si reportas dolor relevante, fatiga muy alta o RPE extremo, CV Coach bloqueará la progresión automática y lo dejará para revisión.</div><div class="cvFeedbackActions"><button id="cvFeedbackCancel" class="btn" type="button">VOLVER AL ENTRENAMIENTO</button><button id="cvFeedbackFinish" class="btn primary" type="button">GUARDAR Y FINALIZAR</button></div><div id="cvFeedbackStatus" class="cvFeedbackStatus"></div></div>';document.body.appendChild(modal);document.getElementById('cvFeedbackCancel').onclick=cvCloseWorkoutFeedback;document.getElementById('cvFeedbackFinish').onclick=()=>cvCompleteWorkoutAfterFeedback(document.getElementById('cvFeedbackStatus'),document.getElementById('cvFeedbackFinish'))}
window.finishWorkout=async()=>{if(mode==='demo'){toast('Demo finalizada. No se escribieron datos.');workout=null;view='home';render();return}if(!workout.sessionId)return toast('Primero inicia el entrenamiento.');cvOpenWorkoutFeedback()}'''
replace_once(old,new,'finish workout feedback flow')

required=['cv-workout-feedback-v1-css','save_workout_feedback','cvFeedbackEffort','cvFeedbackFatigue','cvFeedbackPain','GUARDAR Y FINALIZAR','cvOpenWorkoutFeedback','cvCompleteWorkoutAfterFeedback']
missing=[x for x in required if x not in text]
if missing: raise SystemExit('Missing feedback markers: '+', '.join(missing))
if old in text: raise SystemExit('Legacy direct completion function still present')
path.write_text(text)
