from pathlib import Path

path=Path('client-portal/index.html')
text=path.read_text()

def replace_once(old,new,label):
    global text
    count=text.count(old)
    if count!=1:
        raise SystemExit(f'{label}: expected exactly one anchor, found {count}')
    text=text.replace(old,new,1)

css='''\n<style id="cv-weekly-checkin-v1-css">\n.cvWeeklyCard{border-color:rgba(255,45,63,.34)!important;background:radial-gradient(circle at 100% 0,rgba(225,29,46,.10),transparent 36%),linear-gradient(155deg,#0e151b,#080d11)!important}.cvWeeklyTop{display:flex;gap:10px;align-items:flex-start}.cvWeeklyTop .grow h2{font-size:27px;margin-top:2px}.cvWeeklyBadge{display:inline-flex;border:1px solid #5c4926;border-radius:999px;padding:5px 8px;font-size:8px;font-weight:900;color:#ffd18a;background:#21170a}.cvWeeklyBadge.done{border-color:#31503e;color:#75edb0;background:#10251a}.cvWeeklyMetrics{display:grid;grid-template-columns:repeat(2,1fr);gap:7px;margin:11px 0}.cvWeeklyMetric{border:1px solid #27333a;border-radius:11px;background:#070c10;padding:9px}.cvWeeklyMetric small{display:block;font-size:7px;color:#8f9aa1;text-transform:uppercase;letter-spacing:.08em}.cvWeeklyMetric b{display:block;margin-top:4px;font:800 19px 'Barlow Condensed'}.cvWeeklyBackdrop{position:fixed;inset:0;z-index:270;background:rgba(0,0,0,.84);backdrop-filter:blur(8px);display:flex;align-items:flex-end;justify-content:center;padding:14px}.cvWeeklyModal{width:min(580px,100%);max-height:94dvh;overflow:auto;border:1px solid #303a42;border-radius:20px;background:linear-gradient(155deg,#0d141a,#070b0f);box-shadow:0 30px 95px rgba(0,0,0,.68);padding:18px}.cvWeeklyModal h2{font-size:31px;margin:4px 0 6px}.cvWeeklyGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:9px}.cvWeeklyModal select,.cvWeeklyModal textarea,.cvWeeklyModal input[type="number"]{width:100%;background:#05090d;border:1px solid #303942;color:#fff;border-radius:12px;min-height:46px;padding:10px 12px;font:inherit;outline:none}.cvWeeklyModal textarea{min-height:82px;resize:vertical}.cvWeeklyModal select:focus,.cvWeeklyModal textarea:focus,.cvWeeklyModal input:focus{border-color:rgba(255,45,63,.86);box-shadow:0 0 0 3px rgba(255,45,63,.09)}.cvWeeklyActions{display:grid;grid-template-columns:1fr 1.25fr;gap:8px;margin-top:14px}.cvWeeklyStatus{min-height:20px;margin-top:8px;font-size:11px;color:#aeb8be}.cvWeeklyStatus.error{color:#ff8d99}.cvWeeklySafety{margin-top:10px;padding:10px 12px;border:1px solid #3b3437;border-radius:12px;background:rgba(225,29,46,.055);font-size:10px;line-height:1.45;color:#c4cdd2}@media(min-width:700px){.cvWeeklyBackdrop{align-items:center}.cvWeeklyMetrics{grid-template-columns:repeat(5,1fr)}}@media(max-width:420px){.cvWeeklyGrid{grid-template-columns:1fr}.cvWeeklyActions{grid-template-columns:1fr}}\n</style>\n'''
if '</head>' not in text: raise SystemExit('head close missing')
text=text.replace('</head>',css+'</head>',1)

replace_once(
"sessions:[],trainingHistory:{summary:{window_days:30,terminal_sessions:0,completed_sessions:0,partial_sessions:0,abandoned_sessions:0,total_volume:0,avg_completion:null,last_workout_at:null},sessions:[],records:[]}",
"sessions:[],weeklyCheckins:[],weeklyCheckinsError:'',trainingHistory:{summary:{window_days:30,terminal_sessions:0,completed_sessions:0,partial_sessions:0,abandoned_sessions:0,total_volume:0,avg_completion:null,last_workout_at:null},sessions:[],records:[]}",
'demo weekly state')

replace_once(
"const [p,cp,cv,pr,hab,mis,nt,sessions,history]=await Promise.all([",
"const [p,cp,cv,pr,hab,mis,nt,sessions,checkins,history]=await Promise.all([",
'load destructuring')

replace_once(
"  sb.from('workout_sessions').select('*').eq('client_id',id).order('started_at',{ascending:false}).limit(10),\n  sb.rpc('get_client_training_history',{p_limit:20})",
"  sb.from('workout_sessions').select('*').eq('client_id',id).order('started_at',{ascending:false}).limit(10),\n  sb.from('weekly_checkins').select('*').eq('client_id',id).order('week_start',{ascending:false}).limit(8),\n  sb.rpc('get_client_training_history',{p_limit:20})",
'weekly query')

replace_once(
"sessions:sessions.data||[],trainingHistory:history.error?{error:'Historial no disponible temporalmente.',summary:{},sessions:[],records:[]}:(history.data||{summary:{},sessions:[],records:[]})",
"sessions:sessions.data||[],weeklyCheckins:checkins.error?[]:(checkins.data||[]),weeklyCheckinsError:checkins.error?'Check-in semanal no disponible temporalmente.':'',trainingHistory:history.error?{error:'Historial no disponible temporalmente.',summary:{},sessions:[],records:[]}:(history.data||{summary:{},sessions:[],records:[]})",
'data weekly state')

weekly_js=r'''
function cvChileLocalParts(){const p=new Intl.DateTimeFormat('en',{timeZone:'America/Santiago',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()).reduce((o,x)=>(o[x.type]=x.value,o),{});return {y:Number(p.year),m:Number(p.month),d:Number(p.day)}}
function cvChileWeekStart(){const p=cvChileLocalParts(),dt=new Date(Date.UTC(p.y,p.m-1,p.d)),dow=dt.getUTCDay(),shift=(dow+6)%7;dt.setUTCDate(dt.getUTCDate()-shift);return dt.getUTCFullYear()+'-'+String(dt.getUTCMonth()+1).padStart(2,'0')+'-'+String(dt.getUTCDate()).padStart(2,'0')}
function cvWeeklyCheckins(){return Array.isArray(data?.weeklyCheckins)?data.weeklyCheckins:[]}
function cvWeeklyCurrent(){const week=cvChileWeekStart();return cvWeeklyCheckins().find(x=>String(x.week_start)===week)||null}
function cvWeeklyValue(value,suffix=''){return value==null||value===''?'—':String(value)+suffix}
function cvWeeklyCard(){const current=cvWeeklyCurrent(),unavailable=data?.weeklyCheckinsError||'',done=!!current;if(mode!=='real')return '<section class="section"><div class="card cvWeeklyCard"><div class="ey">CHECK-IN SEMANAL</div><h2>RECUPERACIÓN</h2><div class="hint" style="margin-top:6px">Disponible al iniciar sesión con tu cuenta.</div></div></section>';return '<section class="section"><div class="card cvWeeklyCard"><div class="cvWeeklyTop"><div class="grow"><div class="ey">CHECK-IN SEMANAL</div><h2>RECUPERACIÓN</h2><div class="hint">Sueño, energía, estrés y molestias ayudan a adaptar el entrenamiento con más contexto.</div></div><span class="cvWeeklyBadge '+(done?'done':'')+'">'+(done?'ENVIADO':'PENDIENTE')+'</span></div>'+(unavailable?'<div class="hint" style="margin-top:10px;color:#ffd18a">'+esc(unavailable)+'</div>':'')+(current?'<div class="cvWeeklyMetrics"><div class="cvWeeklyMetric"><small>Sueño</small><b>'+esc(cvWeeklyValue(current.sleep_hours_avg,' h'))+'</b></div><div class="cvWeeklyMetric"><small>Energía</small><b>'+esc(cvWeeklyValue(current.energy_level,' / 5'))+'</b></div><div class="cvWeeklyMetric"><small>Estrés</small><b>'+esc(cvWeeklyValue(current.stress_level,' / 5'))+'</b></div><div class="cvWeeklyMetric"><small>Rigidez</small><b>'+esc(cvWeeklyValue(current.soreness_score,' / 10'))+'</b></div><div class="cvWeeklyMetric"><small>Dolor</small><b>'+esc(cvWeeklyValue(current.pain_score,' / 10'))+'</b></div></div>':'<div class="hint" style="margin:12px 0">Aún no has enviado el check-in de esta semana.</div>')+'<button class="btn primary" type="button" onclick="openWeeklyCheckin()">'+(done?'ACTUALIZAR CHECK-IN':'HACER CHECK-IN · 1 MIN')+'</button></div></section>'}
function cvWeeklyOptions(min,max,value){let out='';for(let i=min;i<=max;i++)out+='<option value="'+i+'" '+(Number(value)===i?'selected':'')+'>'+i+'</option>';return out}
function openWeeklyCheckin(){if(mode!=='real'||!user?.id)return toast('Inicia sesión para completar tu check-in.');const c=cvWeeklyCurrent()||{};let root=document.getElementById('cvWeeklyBackdrop');if(root)root.remove();root=document.createElement('div');root.id='cvWeeklyBackdrop';root.className='cvWeeklyBackdrop';root.innerHTML='<form class="cvWeeklyModal" onsubmit="saveWeeklyCheckin(event)"><div class="row"><div class="grow"><div class="ey">CHECK-IN SEMANAL</div><h2>¿CÓMO LLEGAS ESTA SEMANA?</h2></div><button id="cvWeeklyClose" class="btn" type="button">✕</button></div><div class="sub">Responde con tu estado real. Esto no es un diagnóstico médico; sirve para ajustar el entrenamiento y priorizar revisión del coach cuando corresponda.</div><div class="cvWeeklyGrid"><div><label>Sueño promedio · horas</label><input id="cvWeeklySleep" type="number" min="0" max="14" step="0.5" required value="'+esc(c.sleep_hours_avg??7)+'"></div><div><label>Calidad del sueño · 1–5</label><select id="cvWeeklySleepQuality" required>'+cvWeeklyOptions(1,5,c.sleep_quality??3)+'</select></div><div><label>Energía · 1–5</label><select id="cvWeeklyEnergy" required>'+cvWeeklyOptions(1,5,c.energy_level??3)+'</select></div><div><label>Estrés · 1–5</label><select id="cvWeeklyStress" required>'+cvWeeklyOptions(1,5,c.stress_level??3)+'</select></div><div><label>Rigidez / agujetas · 0–10</label><select id="cvWeeklySoreness" required>'+cvWeeklyOptions(0,10,c.soreness_score??0)+'</select></div><div><label>Dolor / molestia · 0–10</label><select id="cvWeeklyPain" required>'+cvWeeklyOptions(0,10,c.pain_score??0)+'</select></div><div><label>Motivación · 1–5</label><select id="cvWeeklyMotivation">'+cvWeeklyOptions(1,5,c.motivation_level??3)+'</select></div><div><label>Días disponibles próxima semana · 0–7</label><select id="cvWeeklyDays">'+cvWeeklyOptions(0,7,c.available_days_next_week??3)+'</select></div></div><label>Si hay molestia, cuéntame dónde o cuándo aparece · opcional</label><textarea id="cvWeeklyPainNotes" maxlength="500" placeholder="Ej.: rodilla al bajar escaleras…">'+esc(c.pain_notes||'')+'</textarea><label>Algo más que deba considerar · opcional</label><textarea id="cvWeeklyNotes" maxlength="1000" placeholder="Sueño, trabajo, horarios, recuperación…">'+esc(c.notes||'')+'</textarea><div class="cvWeeklySafety">Dolor relevante, sueño muy bajo junto con energía baja u otras señales de recuperación pueden pausar una progresión automática y avisar al coach.</div><div class="cvWeeklyActions"><button id="cvWeeklyCancel" class="btn" type="button">CANCELAR</button><button id="cvWeeklySubmit" class="btn primary" type="submit">GUARDAR CHECK-IN</button></div><div id="cvWeeklyStatus" class="cvWeeklyStatus" role="status"></div></form>';document.body.append(root);const close=()=>root.remove();document.getElementById('cvWeeklyClose').onclick=close;document.getElementById('cvWeeklyCancel').onclick=close}
async function saveWeeklyCheckin(event){event.preventDefault();if(mode!=='real'||!user?.id)return;const button=document.getElementById('cvWeeklySubmit'),status=document.getElementById('cvWeeklyStatus');try{button.disabled=true;status.className='cvWeeklyStatus';status.textContent='Guardando check-in…';const payload={p_sleep_hours_avg:Number(document.getElementById('cvWeeklySleep').value),p_sleep_quality:Number(document.getElementById('cvWeeklySleepQuality').value),p_energy_level:Number(document.getElementById('cvWeeklyEnergy').value),p_stress_level:Number(document.getElementById('cvWeeklyStress').value),p_soreness_score:Number(document.getElementById('cvWeeklySoreness').value),p_pain_score:Number(document.getElementById('cvWeeklyPain').value),p_pain_notes:document.getElementById('cvWeeklyPainNotes').value.trim()||null,p_motivation_level:Number(document.getElementById('cvWeeklyMotivation').value),p_available_days_next_week:Number(document.getElementById('cvWeeklyDays').value),p_notes:document.getElementById('cvWeeklyNotes').value.trim()||null};if(!Number.isFinite(payload.p_sleep_hours_avg)||payload.p_sleep_hours_avg<0||payload.p_sleep_hours_avg>14)throw new Error('Revisa las horas de sueño.');const result=await sb.rpc('submit_weekly_checkin',payload);if(result.error)throw result.error;const saved=result.data?.checkin,risk=result.data?.risk;if(!saved?.id)throw new Error('El servidor no confirmó el check-in.');const q=await sb.from('weekly_checkins').select('*').eq('client_id',user.id).order('week_start',{ascending:false}).limit(8);if(q.error)throw q.error;data.weeklyCheckins=q.data||[];data.weeklyCheckinsError='';document.getElementById('cvWeeklyBackdrop')?.remove();render();if(risk?.level==='RED')toast('Check-in guardado · tu coach recibió una alerta prioritaria.');else if(risk?.level==='YELLOW')toast('Check-in guardado · tu coach revisará tu recuperación.');else toast('Check-in semanal guardado.')}catch(error){status.className='cvWeeklyStatus error';status.textContent='No pude guardar el check-in: '+String(error?.message||error)}finally{button.disabled=false}}
'''
replace_once('function progress(){',weekly_js+'\nfunction progress(){','weekly helpers')

old='''function progress(){const h=cvTrainingHistory(),s=h.summary||{},volume=cvTrainingNum(s.total_volume),avg=cvTrainingNum(s.avg_completion);return `<div class="ey">SEGUIMIENTO</div><h1 style="font-size:39px;margin:5px 0">TU PROGRESO</h1><div class="sub">Historial real de entrenamiento, marcas registradas, logros y progreso visual.</div>${h.error?'''
new='''function progress(){const h=cvTrainingHistory(),s=h.summary||{},volume=cvTrainingNum(s.total_volume),avg=cvTrainingNum(s.avg_completion);return `<div class="ey">SEGUIMIENTO</div><h1 style="font-size:39px;margin:5px 0">TU PROGRESO</h1><div class="sub">Historial real de entrenamiento, marcas registradas, recuperación, logros y progreso visual.</div>${cvWeeklyCard()}${h.error?'''
replace_once(old,new,'progress weekly card')

required=['cv-weekly-checkin-v1-css','weekly_checkins',"sb.rpc('submit_weekly_checkin'",'HACER CHECK-IN · 1 MIN','weeklyCheckinsError','cvChileWeekStart','weekly_recovery']
missing=[x for x in required if x not in text]
if missing: raise SystemExit('Missing weekly check-in markers: '+', '.join(missing))
path.write_text(text)
