from pathlib import Path

path = Path('index.html')
text = path.read_text(encoding='utf-8')
original = text

old_card_tail = '''${draft?`<button class="btn small exerciseDelete" style="margin-top:8px" data-id="${esc(a.id)}">ELIMINAR ASIGNACIÓN</button>`:''}</div>`'''
new_card_tail = '''${draft?`<div class="inlineExerciseEditor" data-id="${esc(a.id)}" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(92px,1fr));gap:8px;margin-top:10px;padding-top:10px;border-top:1px solid var(--b)"><label style="font-size:10px;color:var(--m)">Series<input class="input inlineExerciseInput" data-field="target_sets" type="number" min="1" max="10" step="1" value="${esc(a.target_sets??'')}" style="margin:4px 0 0;padding:8px"></label><label style="font-size:10px;color:var(--m)">Reps mín.<input class="input inlineExerciseInput" data-field="rep_min" type="number" min="1" max="100" step="1" value="${esc(a.rep_min??'')}" style="margin:4px 0 0;padding:8px"></label><label style="font-size:10px;color:var(--m)">Reps máx.<input class="input inlineExerciseInput" data-field="rep_max" type="number" min="1" max="100" step="1" value="${esc(a.rep_max??'')}" style="margin:4px 0 0;padding:8px"></label><label style="font-size:10px;color:var(--m)">RIR<input class="input inlineExerciseInput" data-field="rir_target" type="number" min="0" max="10" step="0.1" value="${esc(a.rir_target??'')}" style="margin:4px 0 0;padding:8px"></label><label style="font-size:10px;color:var(--m)">Descanso s<input class="input inlineExerciseInput" data-field="rest_seconds" type="number" min="0" max="900" step="1" value="${esc(a.rest_seconds??'')}" style="margin:4px 0 0;padding:8px"></label><label style="font-size:10px;color:var(--m)">Peso kg<input class="input inlineExerciseInput" data-field="initial_weight_kg" type="number" min="0" max="1000" step="0.01" value="${esc(a.initial_weight_kg??'')}" style="margin:4px 0 0;padding:8px"></label><div style="grid-column:1/-1" class="row"><button class="btn good small inlineExerciseSave" data-id="${esc(a.id)}">GUARDAR PARÁMETROS</button><span class="inlineExerciseStatus muted grow"></span></div></div><button class="btn small exerciseDelete" style="margin-top:8px" data-id="${esc(a.id)}">ELIMINAR ASIGNACIÓN</button>`:''}</div>`'''
if old_card_tail not in text:
    raise SystemExit('exercise card anchor not found')
text = text.replace(old_card_tail, new_card_tail, 1)

old_handlers = '''$$('.changeExercise').forEach(b=>b.onclick=()=>openExerciseAlternatives(id,assignments.find(x=>x.id===b.dataset.id),allExercises,[]));$$('.exerciseDelete').forEach'''
new_handlers = r'''$$('.changeExercise').forEach(b=>b.onclick=()=>openExerciseAlternatives(id,assignments.find(x=>x.id===b.dataset.id),allExercises,[]));$$('.inlineExerciseSave').forEach(b=>b.onclick=async()=>{let box=b.closest('.inlineExerciseEditor'),status=box?.querySelector('.inlineExerciseStatus'),input=field=>box?.querySelector('[data-field="'+field+'"]'),read=(field,label,{required=false,integer=false,min=0,max=null}={})=>{let raw=input(field)?.value.trim()??'';if(raw===''){if(required)throw Error(label+' es obligatorio.');return null}let n=Number(raw);if(!Number.isFinite(n)||(integer&&!Number.isInteger(n))||n<min||(max!==null&&n>max))throw Error(label+' debe estar entre '+min+' y '+max+(integer?' y ser entero':'')+'.');return n};try{b.disabled=true;b.textContent='GUARDANDO…';if(status)status.textContent='';let target_sets=read('target_sets','Series',{required:true,integer:true,min:1,max:10}),rep_min=read('rep_min','Reps mínimas',{integer:true,min:1,max:100}),rep_max=read('rep_max','Reps máximas',{integer:true,min:1,max:100}),rir_target=read('rir_target','RIR',{min:0,max:10}),rest_seconds=read('rest_seconds','Descanso',{integer:true,min:0,max:900}),initial_weight_kg=read('initial_weight_kg','Peso',{min:0,max:1000});if(rep_min!==null&&rep_max!==null&&rep_max<rep_min)throw Error('Las reps máximas no pueden ser menores que las mínimas.');await ensureDraft(id);await req('/rest/v1/program_exercises?id=eq.'+encodeURIComponent(b.dataset.id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({target_sets,rep_min,rep_max,rir_target,rest_seconds,initial_weight_kg})});cache={};toast('Parámetros guardados.');await programEditor(id)}catch(e){if(status)status.textContent='No se pudo guardar: '+String(e?.message||e);b.disabled=false;b.textContent='GUARDAR PARÁMETROS'}});$$('.exerciseDelete').forEach'''
if old_handlers not in text:
    raise SystemExit('exercise handler anchor not found')
text = text.replace(old_handlers, new_handlers, 1)

if text == original:
    raise SystemExit('No changes made')
path.write_text(text, encoding='utf-8')
print('Inline exercise editing patch applied')
