-- CV Coach V76 — production canary isolation and receipts
-- The canary exercises the real athlete workflow while keeping QA traffic out of
-- CV Score, outbox/AI processing and progression invalidation.

create table if not exists public.cv_canary_clients (
  client_id uuid primary key references public.profiles(id) on delete cascade,
  label text not null unique,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.cv_canary_clients enable row level security;
revoke all on table public.cv_canary_clients from anon, authenticated;
grant select, insert, update, delete on table public.cv_canary_clients to service_role;

create table if not exists public.cv_canary_runs (
  run_id text primary key,
  client_id uuid not null references public.profiles(id) on delete restrict,
  session_id uuid,
  status text not null check (status in ('bootstrapped','claimed','verified','cleaned','failed')),
  baseline jsonb not null default '{}'::jsonb,
  result jsonb not null default '{}'::jsonb,
  error_text text,
  started_at timestamptz not null default now(),
  claimed_at timestamptz,
  verified_at timestamptz,
  cleaned_at timestamptz,
  updated_at timestamptz not null default now()
);

alter table public.cv_canary_runs enable row level security;
revoke all on table public.cv_canary_runs from anon, authenticated;
grant select, insert, update, delete on table public.cv_canary_runs to service_role;

create index if not exists idx_cv_canary_runs_client_started
  on public.cv_canary_runs(client_id, started_at desc);
create index if not exists idx_cv_canary_runs_status_started
  on public.cv_canary_runs(status, started_at desc);

do $$
declare
  v_count integer;
  v_client_id uuid;
begin
  select count(*), min(id)
  into v_count, v_client_id
  from public.profiles
  where role::text='client'
    and lower(btrim(coalesce(first_name,'')))='cliente'
    and lower(btrim(coalesce(last_name,'')))='prueba';

  if v_count <> 1 or v_client_id is null then
    raise exception 'V76 requires exactly one enabled QA profile named Cliente Prueba; found %', v_count;
  end if;

  if not exists(select 1 from auth.users u where u.id=v_client_id) then
    raise exception 'V76 QA profile has no matching auth user';
  end if;

  insert into public.cv_canary_clients(client_id,label,enabled,updated_at)
  values(v_client_id,'production-v76',true,now())
  on conflict(label) do update
    set client_id=excluded.client_id,
        enabled=true,
        updated_at=now();
end
$$;

create or replace function private.is_cv_canary_client(p_client_id uuid)
returns boolean
language sql
stable
security definer
set search_path=''
as $$
  select exists(
    select 1
    from public.cv_canary_clients c
    where c.client_id=p_client_id
      and c.enabled=true
  );
$$;

revoke all on function private.is_cv_canary_client(uuid) from public, anon, authenticated;
grant execute on function private.is_cv_canary_client(uuid) to service_role;

-- Preserve normal CV Score behavior for every real client. Only workout-session
-- triggers generated by the dedicated canary account are suppressed.
create or replace function private.recalculate_cv_score_trigger()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
declare v_client uuid;
begin
  if tg_op='DELETE' then v_client:=old.client_id; else v_client:=new.client_id; end if;
  if tg_table_name='workout_sessions' and private.is_cv_canary_client(v_client) then
    return null;
  end if;
  if v_client is not null then
    perform private.calculate_cv_score_core(v_client,null,'trigger:'||tg_table_name);
  end if;
  return null;
end;
$$;

create or replace function private.workout_outbox_on_insert()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
begin
  if private.is_cv_canary_client(new.client_id) then
    return new;
  end if;
  perform private.enqueue_event(
    'WORKOUT_STARTED','workout_session',new.id,new.client_id,
    jsonb_build_object(
      'session_id',new.id,'client_id',new.client_id,'program_id',new.program_id,
      'program_day_id',new.program_day_id,'status',new.status::text,'started_at',new.started_at
    ),
    'workout:'||new.id::text||':started',new.started_at
  );
  return new;
end;
$$;

create or replace function private.workout_outbox_on_finish()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
declare
  v_event text;
  v_event_id uuid;
  v_payload jsonb;
  v_level public.risk_level;
  v_score integer;
  v_reason_code text;
  v_reason_text text;
begin
  if private.is_cv_canary_client(new.client_id) then
    return new;
  end if;

  if old.status::text='in_progress' and new.status::text<>'in_progress' then
    v_event:=case when new.status::text='abandoned' then 'WORKOUT_ABANDONED' else 'WORKOUT_COMPLETED' end;
    v_payload:=jsonb_build_object(
      'session_id',new.id,'client_id',new.client_id,'program_id',new.program_id,
      'program_day_id',new.program_day_id,'status',new.status::text,
      'completion_pct',new.completion_pct,'duration_seconds',new.duration_seconds,
      'total_volume',new.total_volume,'started_at',new.started_at,'finished_at',new.finished_at,
      'client_effort',new.client_effort,'fatigue_score',new.fatigue_score,
      'pain_score',new.pain_score,'pain_notes',new.pain_notes,'session_notes',new.session_notes
    );

    v_event_id:=private.enqueue_event(
      v_event,'workout_session',new.id,new.client_id,v_payload,
      'workout:'||new.id::text||':'||lower(v_event),coalesce(new.finished_at,now())
    );

    if coalesce(new.pain_score,0)>=7 then
      v_level:='RED'::public.risk_level;
      v_score:=85;
      v_reason_code:='high_pain_feedback';
      v_reason_text:='El alumno reportó dolor alto al finalizar la sesión. Requiere revisión del coach antes de progresar.';
    elsif coalesce(new.pain_score,0)>=4 then
      v_level:='YELLOW'::public.risk_level;
      v_score:=60;
      v_reason_code:='pain_feedback_review';
      v_reason_text:='El alumno reportó dolor relevante al finalizar la sesión. Revisar antes de progresar.';
    elsif coalesce(new.fatigue_score,0)>=8 or coalesce(new.client_effort,0)>=9 then
      v_level:='YELLOW'::public.risk_level;
      v_score:=50;
      if coalesce(new.fatigue_score,0)>=8 and coalesce(new.client_effort,0)>=9 then
        v_reason_code:='high_effort_and_fatigue_feedback';
        v_reason_text:='El alumno reportó RPE global y fatiga altos al finalizar la sesión. Revisar recuperación antes de progresar.';
      elsif coalesce(new.fatigue_score,0)>=8 then
        v_reason_code:='high_fatigue_feedback';
        v_reason_text:='El alumno reportó fatiga alta al finalizar la sesión. Revisar recuperación antes de progresar.';
      else
        v_reason_code:='high_session_effort';
        v_reason_text:='El alumno reportó RPE global alto al finalizar la sesión. Revisar recuperación antes de progresar.';
      end if;
    else
      v_level:=null;
    end if;

    if v_level is not null then
      perform public.apply_workout_risk_assessment(
        new.client_id,new.id,v_event_id,v_level,v_score,v_reason_code,v_reason_text,true
      );
    end if;
  end if;
  return new;
end;
$$;

create or replace function private.invalidate_superseded_progressions_trigger()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
begin
  if private.is_cv_canary_client(new.client_id) then
    return new;
  end if;
  if old.status::text='in_progress' and new.status::text in ('completed','partial','abandoned') then
    perform private.invalidate_superseded_progressions_for_session(new.id);
  end if;
  return new;
end;
$$;

comment on table public.cv_canary_clients is 'Locked service-role registry for isolated production canary identities.';
comment on table public.cv_canary_runs is 'Service-role-only receipts for CV Coach production canary runs.';
